/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StacksStackNameRouteImport } from './routes/stacks.$stackName'
import { Route as ContainersContainerIdRouteImport } from './routes/containers.$containerId'
import { Route as StacksStackNameIndexRouteImport } from './routes/stacks.$stackName.index'
import { Route as StacksStackNameEditRouteImport } from './routes/stacks.$stackName.edit'
import { Route as ContainersContainerIdExecRouteImport } from './routes/containers_.$containerId.exec'

const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksStackNameRoute = StacksStackNameRouteImport.update({
  id: '/stacks/$stackName',
  path: '/stacks/$stackName',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdRoute = ContainersContainerIdRouteImport.update({
  id: '/containers/$containerId',
  path: '/containers/$containerId',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksStackNameIndexRoute = StacksStackNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StacksStackNameRoute,
} as any)
const StacksStackNameEditRoute = StacksStackNameEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => StacksStackNameRoute,
} as any)
const ContainersContainerIdExecRoute =
  ContainersContainerIdExecRouteImport.update({
    id: '/containers_/$containerId/exec',
    path: '/containers/$containerId/exec',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/stacks/$stackName': typeof StacksStackNameRouteWithChildren
  '/containers/$containerId/exec': typeof ContainersContainerIdExecRoute
  '/stacks/$stackName/edit': typeof StacksStackNameEditRoute
  '/stacks/$stackName/': typeof StacksStackNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/containers/$containerId/exec': typeof ContainersContainerIdExecRoute
  '/stacks/$stackName/edit': typeof StacksStackNameEditRoute
  '/stacks/$stackName': typeof StacksStackNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/updates': typeof UpdatesRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/stacks/$stackName': typeof StacksStackNameRouteWithChildren
  '/containers_/$containerId/exec': typeof ContainersContainerIdExecRoute
  '/stacks/$stackName/edit': typeof StacksStackNameEditRoute
  '/stacks/$stackName/': typeof StacksStackNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/updates'
    | '/containers/$containerId'
    | '/stacks/$stackName'
    | '/containers/$containerId/exec'
    | '/stacks/$stackName/edit'
    | '/stacks/$stackName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/updates'
    | '/containers/$containerId'
    | '/containers/$containerId/exec'
    | '/stacks/$stackName/edit'
    | '/stacks/$stackName'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/updates'
    | '/containers/$containerId'
    | '/stacks/$stackName'
    | '/containers_/$containerId/exec'
    | '/stacks/$stackName/edit'
    | '/stacks/$stackName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  UpdatesRoute: typeof UpdatesRoute
  ContainersContainerIdRoute: typeof ContainersContainerIdRoute
  StacksStackNameRoute: typeof StacksStackNameRouteWithChildren
  ContainersContainerIdExecRoute: typeof ContainersContainerIdExecRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$stackName': {
      id: '/stacks/$stackName'
      path: '/stacks/$stackName'
      fullPath: '/stacks/$stackName'
      preLoaderRoute: typeof StacksStackNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId': {
      id: '/containers/$containerId'
      path: '/containers/$containerId'
      fullPath: '/containers/$containerId'
      preLoaderRoute: typeof ContainersContainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$stackName/': {
      id: '/stacks/$stackName/'
      path: '/'
      fullPath: '/stacks/$stackName/'
      preLoaderRoute: typeof StacksStackNameIndexRouteImport
      parentRoute: typeof StacksStackNameRoute
    }
    '/stacks/$stackName/edit': {
      id: '/stacks/$stackName/edit'
      path: '/edit'
      fullPath: '/stacks/$stackName/edit'
      preLoaderRoute: typeof StacksStackNameEditRouteImport
      parentRoute: typeof StacksStackNameRoute
    }
    '/containers_/$containerId/exec': {
      id: '/containers_/$containerId/exec'
      path: '/containers/$containerId/exec'
      fullPath: '/containers/$containerId/exec'
      preLoaderRoute: typeof ContainersContainerIdExecRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StacksStackNameRouteChildren {
  StacksStackNameEditRoute: typeof StacksStackNameEditRoute
  StacksStackNameIndexRoute: typeof StacksStackNameIndexRoute
}

const StacksStackNameRouteChildren: StacksStackNameRouteChildren = {
  StacksStackNameEditRoute: StacksStackNameEditRoute,
  StacksStackNameIndexRoute: StacksStackNameIndexRoute,
}

const StacksStackNameRouteWithChildren = StacksStackNameRoute._addFileChildren(
  StacksStackNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  UpdatesRoute: UpdatesRoute,
  ContainersContainerIdRoute: ContainersContainerIdRoute,
  StacksStackNameRoute: StacksStackNameRouteWithChildren,
  ContainersContainerIdExecRoute: ContainersContainerIdExecRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
