/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContainersContainerIdRouteImport } from './routes/containers.$containerId'
import { Route as StacksStackNameEditRouteImport } from './routes/stacks.$stackName.edit'
import { Route as ContainersContainerIdExecRouteImport } from './routes/containers_.$containerId.exec'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdRoute = ContainersContainerIdRouteImport.update({
  id: '/containers/$containerId',
  path: '/containers/$containerId',
  getParentRoute: () => rootRouteImport,
} as any)
const StacksStackNameEditRoute = StacksStackNameEditRouteImport.update({
  id: '/stacks/$stackName/edit',
  path: '/stacks/$stackName/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainersContainerIdExecRoute =
  ContainersContainerIdExecRouteImport.update({
    id: '/containers_/$containerId/exec',
    path: '/containers/$containerId/exec',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/containers/$containerId/exec': typeof ContainersContainerIdExecRoute
  '/stacks/$stackName/edit': typeof StacksStackNameEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/containers/$containerId/exec': typeof ContainersContainerIdExecRoute
  '/stacks/$stackName/edit': typeof StacksStackNameEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/containers/$containerId': typeof ContainersContainerIdRoute
  '/containers_/$containerId/exec': typeof ContainersContainerIdExecRoute
  '/stacks/$stackName/edit': typeof StacksStackNameEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/containers/$containerId'
    | '/containers/$containerId/exec'
    | '/stacks/$stackName/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/containers/$containerId'
    | '/containers/$containerId/exec'
    | '/stacks/$stackName/edit'
  id:
    | '__root__'
    | '/'
    | '/containers/$containerId'
    | '/containers_/$containerId/exec'
    | '/stacks/$stackName/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContainersContainerIdRoute: typeof ContainersContainerIdRoute
  ContainersContainerIdExecRoute: typeof ContainersContainerIdExecRoute
  StacksStackNameEditRoute: typeof StacksStackNameEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers/$containerId': {
      id: '/containers/$containerId'
      path: '/containers/$containerId'
      fullPath: '/containers/$containerId'
      preLoaderRoute: typeof ContainersContainerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stacks/$stackName/edit': {
      id: '/stacks/$stackName/edit'
      path: '/stacks/$stackName/edit'
      fullPath: '/stacks/$stackName/edit'
      preLoaderRoute: typeof StacksStackNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/containers_/$containerId/exec': {
      id: '/containers_/$containerId/exec'
      path: '/containers/$containerId/exec'
      fullPath: '/containers/$containerId/exec'
      preLoaderRoute: typeof ContainersContainerIdExecRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContainersContainerIdRoute: ContainersContainerIdRoute,
  ContainersContainerIdExecRoute: ContainersContainerIdExecRoute,
  StacksStackNameEditRoute: StacksStackNameEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
